### ISSUE TITLE
Allow annotations on list object

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld-star#10]
A list object, which is the direct value of a node object, should be able to contain an `@annotation`. For example:

```json
{
  "@id": "ex:subject",
  "ex:values": {
    "@list": [1, 2, 3],
    "@annotation": {
      "ex:asOf": {"ex:asOf": "yesterday"}
   }
}
```

would be the same as the following Turtle*:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<ex:subject> <ex:values> _:li .
_:li rdf:first 1; rdf_rest (2 3); <ex:asOf> "yesterday" .
```

**Comment by pchampin** [comment]
I think what you meant was
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<ex:subject> <ex:values> _:li  {| <ex:asOf> "yesterday"  [}.
_:li rdf:first 1; rdf_rest (2 3).
```
or, more simply:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<ex:subject> <ex:values> (1 2 3) {| <ex:asOf> "yesterday" |}.
```

**Comment by gkellogg** [comment]
I spent some time on this, and I don't think it's feasible without major updates to algorithms. Expansion and Compaction are easy enough, but Flattening, which is required for ToRDF and Framing, would need to pre-allocated a blank node as part of a list object so that it could be used to create an embedded node/triple.

Looking at the above example, you'd need to replace the `@annotation` with a new embedded node, which would require property referencing the head of the list (or `rdf:nil`), which doesn't exist. Hypothetically, it might look something like the following:

```
{
  "@default": {
    "ex:subject": {
      "ex:values": [{
        "@id": "_:list",
        "@list": [{"@value": 1}, {"@value": 2}, {"@value": 3}]
      }]
    },
    "{\"@id\":\"ex:subject\":\,"ex:values\":[{\"@id":\"_:list\"}]}":
      "ex:asOf": [{"ex:asOf": [{"@value": "yesterday"}]}]
    }
  }
}
```

But, list objects can't have `@id`, and in any case, the ToRDF algorithm has a lot of specialized code for lists.

Extracting the first element of the list (if any) and using `rdf:first`/`rdf:rest` is possible, but nowhere else does JSON-LD do anything special with these properties.

It seems like a lot of work for a marginal use case.

**Comment by gkellogg** [comment]
Some work done on tests is preserved on the https://github.com/json-ld/json-ld-star/tree/list-annotations branch.

**Comment by pchampin** [comment]
Agreed, that's a lot of complication for a marginal use case... Let's drop it.
